### ISSUE TITLE
Bro-OTX Updating Fails - bro-otx.py is in different location than cron expects

### ISSUE THREAD

**Issue by seclyn** [weslambert/securityonion-otx#1]
More of an FYI - I found that my OTX pulses were not being updated after the initial install. Doing some digging I found the CRON job pointing to a bro-otx file that didn't exist. I updated the cron job, and all seems well.
You'll need to update: /etc/cron.d/bro-otx

And replace the command with:
0 * * * * root python /opt/bro/share/bro/policy/bro-otx/bro-otx.py >> /var/log/nsm/bro-otx.log 2>&1

Link To SO Post: https://groups.google.com/forum/#!topic/security-onion/KqCBHaLzVhA

**Comment by weslambert** [comment]
@seclyn,

I went ahead and made commit(s) that should resolve this issue:

https://github.com/weslambert/securityonion-otx/commit/4c44cbb44c7653c8198a09f4ce3985d2989d6154
https://github.com/weslambert/securityonion-otx/commit/544851e62108c626544ade1548e481887483116d

Thanks,
Wes
