### ISSUE TITLE
Issue with running script - Unary operator expected

### ISSUE THREAD

**Issue by theabraxas** [weslambert/securityonion-otx#2]
When going through the provided guide to setup the OTX connector after putting in the API key it runs until near the end where this error appears:

`securityonion-otx: line 76: [: {"name":": unary operator expected There seems to be an issue with your configuration.  Check /nsm/bro/logs/current/reporter.log for clues.`

In order to fix this I modified the `if` statement in line 76 by switching it from single to double brackets `[[ ]]` The new line looks like:

`if [[ `grep otx /nsm/bro/logs/current/loaded_scripts.log` ]]; then`

This solved the error for me and I received a successful message.

**Comment by weslambert** [comment]
Thanks for the heads up, @theabraxas!  I'll take a look at this.

Wes

**Comment by weslambert** [comment]
Confirmed the issue and committed the following fix: https://github.com/weslambert/securityonion-otx/commit/e6cb0fbb3062a60b0f5f36e7a55d45e91315a453.

Thanks,
Wes
